name: domino
description: An experimental virtual dom library, which allows mixing DOM elements with components.
version: 0.2.2-dev
homepage: https://github.com/isoos/domino
authors:
  - Istvan Soos <istvan.soos@gmail.com>
  - Ravi Teja Gudapati <tejainece@gmail.com>

environment:
  sdk: '>=1.20.1 <2.0.0'

dependencies:
  async_tracker: ^0.1.0

dev_dependencies:
  test: ^0.12.30
